---
version: "3.7"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes: #sabnzbd.ini should be relative to docker fs
      - "${MEDIA_SERVER_ROOT}/monitored:/monitored"
      - "${MEDIA_SERVER_CONFIG}/sabnzbd:/config"
      - "${MEDIA_SERVER_CONFIG}/sabnzbd/scripts:/app/sabnzbd/scripts"
      - "${MEDIA_SERVER_MAIN_DOWNLOADS}/complete:/downloads"
      - "${MEDIA_SERVER_MAIN_DOWNLOADS}/incomplete:/incomplete-downloads"
      # - [the scripts dir]:/docker-entrypoint-initdb.d
    ports:
      - 8083:8080
      - 9093:9090
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - "${MEDIA_STORE_0}/multimedia/shows:/tv"
      - "${MEDIA_SERVER_MAIN_DOWNLOADS}/complete:/downloads"
      - "${MEDIA_SERVER_CONFIG}/sonarr:/config"
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - "${MEDIA_SERVER_CONFIG}/jackett:/config"
      - "${MEDIA_SERVER_MAIN_DOWNLOADS}/complete:/downloads"
    ports:
      - 9117:9117
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - VERSION=docker
      - TZ=Asia/Jerusalem
      - PLEX_CLAIM=z6Lvgcs2tr77SE9_XdoA
      - ADVERTISE_IP=http://192.168.1.100:32400/
      - PUID=1000
      - PGID=1000
    volumes:
      #configs
      - "${MEDIA_SERVER_CONFIG}/plex:/config"
      - "${MEDIA_SERVER_CONFIG}/plex-transcode:/transcode"
      # shows
      - "${MEDIA_STORE_0}/multimedia/shows/Comedy:/tv/comedy"
      - "${MEDIA_STORE_0}/multimedia/shows/Drama:/tv/drama"
      - "${MEDIA_STORE_0}/multimedia/shows/cartoons:/tv/cartoons"
      - "${MEDIA_STORE_0}/multimedia/shows/Doco:/tv/doco"
      #movies
      - "$MEDIA_STORE_1/media/movies:/movies"
      
  utorrent:
    container_name: utorrent
    image: ekho/utorrent:latest
    volumes:
      - "${MEDIA_SERVER_CONFIG}/utorrent:/utorrent/settings"
      - "${MEDIA_SERVER_MAIN_DOWNLOADS}/complete:/data"
    environment:
      UID: 1000
      GID: 1000
      webui: ng
      dir_autoload_delete: 1
      dir_download: /data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
